### ISSUE TITLE
User is returned to log-in screen when the app/phone is rotated.

### ISSUE THREAD

**Issue by IsaacHogben** [oatmael/Sneezy#2] opened 2020-07-31 05:12 UTC

**Comment by oatmael** [comment] 2020-08-01 04:36
This was caused by the logout() function being called during the onDestroy() part of the app life-cycle. From my understanding, rotating the phone will destroy the activity and then rebuild it.

Fixed in recent commit.

**Closed by oatmael** 2020-08-01 04:36 UTC
Labels: bug
